### ISSUE TITLE
Complete our bio section

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [MLH-Fellowship/project-snake-snakeeeeeeeee#10]
Just follow the design file in Figma 💯

**Comment by David-Lazaro-Fernandez** [comment]
Task completed, you can see now the changes in the **Our Bio** branch 💟

**Comment by Quantum-Impulse** [comment]
We can close the issue and merge the branch into main if you want.

**Comment by David-Lazaro-Fernandez** [comment]
On my way!
